num1=int(input("Enter first number :"))
num2=int(input("Enter second number :"))
print("Sum of the numbers is :", num1 + num2)
print("Difference of the numbers is :", num1-num2)
print("Product of the numbers is :", num1*num2)
print("Division of the numbers is :",num1/num2)
print("Modulus of the numbers is :", num1%num2)
print("Floor division of the numbers is :", num1//num2)
print("Exponent of the numbers is :", num1**num2)